### ISSUE TITLE
Absolute Output Directories Don't Work

### ISSUE THREAD

**Issue by ralphcallaway** [ChuckJonas/sfdx-git-packager#11]
From my sfdx project folder I'm running `sfdx git:package -d /Users/ralphcallaway/ant/project/deploy` 

The output ends up in `<proj_root>/Users/ralphcallaway/ant/project/deploy`

**Comment by ChuckJonas** [comment]
Should be fixed.

FYI, if you wanted to stop using ant you can run `sfdx force:mdapi:deploy -d deploy/my-package -w 10000 -u my-user`

**Comment by ralphcallaway** [comment]
thanks for the tip will give that a go
