### ISSUE TITLE
Deletions of files from compound metadata should be treated as modification

### ISSUE THREAD

**Issue by ChuckJonas** [ChuckJonas/sfdx-git-packager#13]
When you delete a single file from a folder MD type (static resource, aura component, lwc), it should treat this as a modification.

**Comment by ralphcallaway** [comment]
Does this issues result in errors like this?
 master
(node:14473) ExperimentalWarning: The fs.promises API is experimental
{ [Error: ENOENT: no such file or directory, scandir 'src/main/default/aura/LCC_CRM_Call_Actions_Event']
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'src/main/default/aura/LCC_CRM_Call_Actions_Event' }

**Comment by ChuckJonas** [comment]
Not sure... Do you have a deletion in that folder?

What's the output of:
`> git --no-pager diff --name-status --no-renames`

**Comment by ralphcallaway** [comment]
```
$ git --no-pager diff --name-status --no-renames

$
```

just a blank line, will zip up the project and send it to you
