### ISSUE TITLE
fatal: Invalid object name 'undefined'

### ISSUE THREAD

**Issue by ralphcallaway** [ChuckJonas/sfdx-git-packager#25]
with v0.0.5 getting an error when trying to run, can't seem to get the debugger to pause before the error, seems to be happening with this line

```
Messages.importMessagesDirectory(__dirname);
```

```
➜  project git:(branch) sfdx git:package -d deploy/feature              
fatal: Invalid object name 'undefined'.
```

**Comment by ralphcallaway** [comment]
maybe related to this?

```
➜  sfdx-git-packager git:(master) ✗ sfdx plugins:install sfdx-git-packager
This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: y
Finished digital signature check.
warning "force-source-clean > @oclif/command@1.5.19" has unmet peer dependency "@oclif/plugin-help@^2".
Installing plugin sfdx-git-packager... installed v0.0.5
```

**Comment by ChuckJonas** [comment]
I think this is actually specific to generating from "working copy" (related #24).

If you run `sfdx git:package -d deploy/feature  -s head`, it works for me.

Other bugs with pulling from refs were fixed, but probably broke the working copy flow

**Comment by ChuckJonas** [comment]
and ya, I haven't been able to use the debugger since before the destructive changes.  I've tried a bunch of different launch & ts configs with no luck

**Comment by ChuckJonas** [comment]
Most likely this commit is causing the issue:  https://github.com/ChuckJonas/sfdx-git-packager/commit/029c77773ca70e937368ae0f14e51a1b4e306095

Again, unless there are objections, my preferred fix would just be to remove the ability to target "working copy"

**Comment by ralphcallaway** [comment]
weird the debugger fell apart

so did seem related to #24, `-s head` worked for me, although i had to first deal with `sfdx-project.json` not being present for the project (people have been ignoring)

i can see some use to working copy, but seems fine to drop it, if there is demand we can always get it back

**Comment by ChuckJonas** [comment]
`sfdx-project.json` should always be committed and I think it make more sense to pull it from the ref than working copy (although if you changed package structures... I'm guessing this thing would blow up massively anyways)

**Comment by ralphcallaway** [comment]
totally, if only my team had a .gitignore template, maybe they wouldn't ignore all the good stuff ;-p

**Comment by ralphcallaway** [comment]
fwiw this fails every time if i don't add `-s head`, anyone who uses the tool is going to be impacted

**Comment by ChuckJonas** [comment]
That would mean they were using it to generate vs. working copy...  Which I would be curious if that's what they were actually intending to do (because if it is then maybe #24 needs to be reconsidered).
