### ISSUE TITLE
Default to destructiveChangesPost.xml

### ISSUE THREAD

**Issue by ChuckJonas** [ChuckJonas/sfdx-git-packager#27]
Seems like there are more use-cases in which `destructiveChangesPost.xml` is needed.

For example, if you simply wanted to delete a field and update the apex code that is referencing it.  If you do this with `destructiveChanges.xml`, it will attempt to delete the field before the Apex referencing it has been deployed.

I think we should default to using this instead.  Maybe an param to control (in an ideal world it would be smart enough to know when to use pre vs post).

**Comment by ChuckJonas** [comment]
@ralphcallaway thoughts?

**Comment by ralphcallaway** [comment]
@ChuckJonas dont feel strongly either way, i'm pretty comfortable with any approach, once the package is generated it's pretty quick to adjust it. feels like it would work, most of the deletions are stuff i've removed references too
