### ISSUE TITLE
Generate destructiveChanges.xml

### ISSUE THREAD

**Issue by ChuckJonas** [ChuckJonas/sfdx-git-packager#3]
Create destructive-changes.xml based on deletions.

Probably have an option flag `-d` to turn this on.

**Comment by ralphcallaway** [comment]
would think this should be on by default if the goal is to use this for source control first setups

**Comment by ChuckJonas** [comment]
I think the challenge with deletions is knowing if they need to be part of `destructiveChangesPre.xml` or `destructiveChangesPost.xml` ([reference](https://developer.salesforce.com/docs/atlas.en-us.daas.meta/daas/daas_destructive_changes.htm)). 

I honestly haven't done enough destructive deployments to know all the scenario which you need to use different ones.

**Comment by ralphcallaway** [comment]
woah, i had know idea this existed, i think for the purpose of this feature you'd be good to go with `destructiveChanges.xml` and if people want to split it into pre and post they can do that before doing the deployment ...

**Comment by ChuckJonas** [comment]
ya, even just generating the XML for this feature by itself is not all that simple...  

One thing I just considered (which is broken in the current build), is that if you delete a file from a composite metadata type (`aura`, `lwc`, `staticresource` folder), then it needs to treat that as a change and redeploy the component (instead of destructing the single file).

We would only want to "destruct" these items when the entire folder was removed.  As a cheat, you could just look for the `-meta.xml` file and if it was removed treat it as a delete, even if the source is still in place.

Otherwise, we are going to actually have to map resources to metadata types and generate a `package.xml` (similar to how the old `genpack` created a package.xml).

**Comment by ChuckJonas** [comment]
yew! 

@ralphcallaway  Thanks for getting this 90% there!
