### ISSUE TITLE
source:convert fails if a space is in target deploy directory.

### ISSUE THREAD

**Issue by Confirm4Crit** [ChuckJonas/sfdx-git-packager#31]
I can flesh this out laster, but at least on MacOS Catalina, target deploy directory can't have a space, doesn't seem like the directory for convert is wrapped in quotes.

**Comment by ChuckJonas** [comment]
can you just copy and paste the command string you are running?  I'm guessing this is the same as #19, but I just want to make sure

**Comment by ChuckJonas** [comment]
should be fixed with 0.1.2

Please update by running `sfdx plugins:install sfdx-git-packager` & test

**Comment by Confirm4Crit** [comment]
@ChuckJonas Will when I can, but offhand, yea, similar structure.
