### ISSUE TITLE
fatal: Path 'force-app/main/default/classes/RandomClass.cls' exists on disk, but not in 'master'.

### ISSUE THREAD

**Issue by ghost** [ChuckJonas/sfdx-git-packager#39]
Running the command : sfdx git:package -d test  -w

If the file is new looks like it's not working correctly 

If we run the command without -w it works ok

**Comment by ChuckJonas** [comment]
yea... I see why this is happening.  We are checking for whitespace diff on every change, but it should really only happen on `modified`.

Shouldn't be too hard to fix.
