### ISSUE TITLE
Doesnt generate destructive package

### ISSUE THREAD

**Issue by rdepaiah** [ChuckJonas/sfdx-git-packager#47]
Hi,
Thanks for this wonderful tool, it's very helpful.

I ran into an issue where it doesnt generate destructive package file 
![image](https://user-images.githubusercontent.com/7824378/98532955-44c44500-227a-11eb-9ee4-3f057e4c8372.png)

When i check on VS code it works fine but on piplelines it doesnt generate one

Please help

Thanks
-Ramesh

**Comment by rdepaiah** [comment]
master branch was not pushed to origin, so it was working on local vs code but not on bitbucket pipeline

**Comment by ChuckJonas** [comment]
@ram4031 👍 

FYI, this works best for CI when the target branch (`master`) is "guaranteed" to be in sync with production.

In our CI we do by performing a "Clean Auto-Checkout" and attempting to merge that commit back into our "Feature" branch.  This ensures there are no conflicts between production and your feature branch.

More documentation on how our CI works, along with our full pipeline scripts, can be [found here](https://github.com/callawaycloud/generator-ccc/blob/master/generators/app/templates/static/build/pipelines-setup.md).
