### ISSUE TITLE
Package is not reset on subsequent runs

### ISSUE THREAD

**Issue by ChuckJonas** [ChuckJonas/sfdx-git-packager#5]
Currently, if you run the same `-d` param, it does not reset the package (IOW generation is additive).

**Comment by ChuckJonas** [comment]
Seems like this would be easy, but it actually requires careful thought and execution because we are going to have to run `rm -rf`...  I'm concerned how we can do this without have the risk of nuking files if a bad parameter is passed in.

I can think of a couple solutions...

1. Try to add "guards".  IOW, don't let them pass values like `/` or `./`...  Even with this guard, you could still do some serious damage if you were to blindly `rm -rf`.  Ruling this out

2. Only remove assets that would actually be generated.  IOW, target `classes`, `pages`, etc.  This would work well, but we would need a complete list of package asset folders. But nice because it's not a breaking change.

3. always create a sub directory for generated files.  IOW, add a default `package` folder that get appended to the `-d` path.

EG: if you passed `-d deployments/my-feature`, the output package would be in `deployments/my-feature/package`.  This is probably the easiest & most complete solution, but will be a breaking change for CI processes (not sure it really matters given how young this project is)

@jake-hebert @ralphcallaway would like to get your thoughts on this

**Comment by ralphcallaway** [comment]
perhaps we just require that the directory be empty or non-existent, if you force it you'll just overwrite (so files that are still in the package are updated, stuff that isn't package would still stick around)
- saves you from having to worry about deleting stuff you shouldn't
- seems a reasonable thing to expect someone else to take care of
- maybe could use it to layer multiple passes, say to merge a couple sources (kind of weird, but i could see it)

in terms of ci, you could also consider an environmental variable for the resulting directory, i.e. GIT_PACKAGE_LAST_DEPLOY_DIR that CI's could pick up on

**Comment by ralphcallaway** [comment]
the sub package idea seems like it's just layer things unless `package` is random, if you the same command twice you're back in the same boat

**Comment by ChuckJonas** [comment]
@ralphcallaway Sorry, I wasn't very clear in explaining 3.  The idea with adding a sub-directory is that you could safety `rm -rf` it, knowing that no matter what path is passed into `-d` you will at least be narrowed down to a sub directory.   The only trouble you could get into would be if you ran it in a directory where there was already a folder named `package` (or whatever else).

EG: even if `/` was passed in, the reset script would be limited to `/package` (where as right now you end up with `/classes`, `/pages`, etc).

But I think you're right... the safest thing to do is just check and error out, although less convenient if you end up having to run it multiple times for some reason.

**Comment by jake-hebert** [comment]
What about creating an additional file with a randomly generated name? Or
(this might be what Ralph is saying), validating that the contents of the
folder you are deleting contains folders that match the names of the
metadata in your package.xml?

**Comment by jake-hebert** [comment]
And I mean, just validate that the randomly generated file or the package
contents is contained in the folder you are trying to delete.

**Comment by ralphcallaway** [comment]
so now that i've been enlightened on using sfdx for deployments instead of using this for ant, realizing that there isn't much of a need to have the output be outside of the project folder

i'd vote to just only do destinations in the current folder, and then wipe the contents of deployable stuff in the folder

one thing you might want to consider around this, with the ant based deployments there were some items you could put in a deployment instructions file, this might be nice if you wanted to add nuanced behavior you wanted to keep in multiple passes (i.e. use pre destructive for some options), so might be some benefit to keeping deletions to known metadata files (probably overkill for current version)

**Comment by ralphcallaway** [comment]
ala jakes suggestion, might also think about just ditching the output folder entirely and just using a timestamp, i.e. deploy_2019....

**Comment by ChuckJonas** [comment]
@ralphcallaway  The problem with a `timestamp` is that it would make scripting more difficult as you would need to discover the destination before being able to run `sfdx force:mdapi:deploy -d /deployments/...`

> i'd vote to just only do destinations in the current folder, and then wipe the contents of deployable stuff in the folder


> one thing you might want to consider around this, with the ant based deployments there were some items you could put in a deployment instructions file, this might be nice if you wanted to add nuanced behavior you wanted to keep in multiple passes (i.e. use pre destructive for some options), so might be some benefit to keeping deletions to known metadata files (probably overkill for current version)

I didn't really follow either of those statements very well... Could you add examples?

**Comment by ralphcallaway** [comment]
> i'd vote to just only do destinations in the current folder, and then wipe the contents of deployable stuff in the folder

yeah, definitely not clear.

meaning if you're project is at `~/dev/my_project`, whatever you pass in for `-d` is relative, hence whatever you're deleting must be a folder in the project, hence the only way to really do damage is to make you're root folder an sfdx project and then run `sfdx git:package -d Users`.

**Comment by ralphcallaway** [comment]
> one thing you might want to consider around this, with the ant based deployments there were some items you could put in a deployment instructions file, this might be nice if you wanted to add nuanced behavior you wanted to keep in multiple passes (i.e. use pre destructive for some options), so might be some benefit to keeping deletions to known metadata files (probably overkill for current version)

you have a project, `~/dev/my_project`, you created a deploy folder `~/dev/my_project/deploy_new_feature`, you add a instruction file ~/dev/my_project/deploy_new_feature/.package` with something like
```
preDelete=CustomObject__c.Field__c
postDelete=CustomObject__c.Temp__c,SweetApp.Page__c
```

then those instructions could get read by `git:package` to decide whether a deleted field goes in `destructiveChanges.xml`/`destructiveChangesPre.xml`/`destructiveChangesPost.xml`, which would be nice if you generate a package and a test fails, and you update that test and regenerate the package, you don't have to deal with split that back up

or more realistically, if you made the `.packageIgnore` file specific to just a specific deployment package you're generating

very round about way of saying the "clean" that happens on subsequent runs might want to exclude files that aren't relevant to the deployment

that said, i'm definitely thinking about things that would matter for v4, so probably not worth designing for yet

**Comment by ChuckJonas** [comment]
> meaning if you're project is at ~/dev/my_project, whatever you pass in for -d is relative, hence whatever you're deleting must be a folder in the project, hence the only way to really do damage is to make you're root folder an sfdx project and then run sfdx git:package -d Users.

gotcha... it does seems like we should be able to support absolute paths tho (not sure why they would really be needed tho).

> you have a project, ~/dev/my_project, you created a deploy folder ~/dev/my_project/deploy_new_feature, you add a instruction file ~/dev/my_project/deploy_new_feature/.package` with something like

ya, I think we could ignore anything that starts with `.`.  It would be better if we could only target valid metadata.  It could possibly be done, if exception are made for static resources.  

> or more realistically, if you made the .packageIgnore file specific to just a specific deployment package you're generating

I think we could probably do a secondary `packageIngore` via a command line prop (either a csv string or link to a different file)

**Comment by ChuckJonas** [comment]
what if we just checked to see if the `-d` file existed.  If it does, then we can prompt the user:

`Package Directory already exists!  How would the like to continue? (purge, merge, exit)`

The implementation would be simple enough, but it would also prevent people from accidentally deleting something important.

**Comment by ralphcallaway** [comment]
> `Package Directory already exists! How would the like to continue? (purge, merge, exit)`

love it
