### ISSUE TITLE
Error on files in non-sfdx project folders

### ISSUE THREAD

**Issue by ralphcallaway** [ChuckJonas/sfdx-git-packager#7]
I have some scripts stored in a `apex-scripts` folder which is not stored in my sfdx-project.json and includes files ending in .cls.

Running the git packager results in an error.
```
{ [Error: ENOENT: no such file or directory, copyfile 'apex-scripts/example.cls-meta.xml' -> '/Users/ralphcallaway/Development/project/.tmp-pkg-prj/apex-scripts/example.cls-meta.xml']
  errno: -2,
  code: 'ENOENT',
  syscall: 'copyfile',
  path: 'apex-scripts/example.cls-meta.xml',
  dest:
   '/Users/ralphcallaway/Development/project/.tmp-pkg-prj/apex-scripts/example.cls-meta.xml' }
```

Ideally the packager would only look at folders specified in `sfdx-project.json`

**Comment by ralphcallaway** [comment]
the `.packageIgnore` file can deal with this, seems like if we're parsing `sfdx-project.json` would be worth sticking to just those folders

**Comment by ChuckJonas** [comment]
ya there's a todo comment to filter out anything that isn't in the `sfdx-project.json` package paths
