### ISSUE TITLE
Errors on Non-Default SFDX package Folders if No Changes

### ISSUE THREAD

**Issue by ralphcallaway** [ChuckJonas/sfdx-git-packager#8]
I have two package folders listed in `sfdx-project.json`, when a change is *NOT* included from a non-default package folder i get the following error

```
ERROR running force:source:convert:  The path /Users/ralphcallaway/Development/project/tmp-pkg-prj/non-default-pkg-folder, specified in sfdx-project.json, does not exist. Be sure this directory is included in your project root.
```

**Comment by ralphcallaway** [comment]
added a temp change to class in the secondary project folder and things worked

**Comment by ChuckJonas** [comment]
I guess the easiest thing to do would just be to initialize a directory for every `packageDirectory` of the `sfdx-project.json` in the .tmp folder
