### ISSUE TITLE
Leaves Temp Folder On Error

### ISSUE THREAD

**Issue by ralphcallaway** [ChuckJonas/sfdx-git-packager#9]
When run and an error is encountered a `.tmp-pkg-prj` folder is left with a number of artifacts in the running directory.

**Comment by ChuckJonas** [comment]
moved cleanup to finally... Unfortunately, if it fails here, then there is really nothing we can do

**Comment by ralphcallaway** [comment]
this probably covers it, but if not you might consider looking at something like https://www.npmjs.com/package/tmp so your artifacts are somewhere they won't cause issues and will eventually get cleaned up

**Comment by ChuckJonas** [comment]
great suggestion... reopening until we can refactor to use `tmp` package

**Comment by ChuckJonas** [comment]
Refactored to use tmp.

@jake-hebert I wonder if this won't fix this issues we were having with rimraf
